# json keys
ZONE_TITLE = "ObjectShortName"
POLYGONS_TITLE = "p_title"
POLYGONS_DATA = "pplygon"
ENTERTAINMENTS_TITLE = "title"
ENTERTAINMENTS_COST = "cost"
ENTERTAINMENTS_LONGITUDE = "lon"
ENTERTAINMENTS_LATITUDE = "lat"
ENTERTAINMENTS_ZONE_TITLE = "ZoneTitle"
ENTERTAINMENTS_SEAT_COUNT = 0
ENTERTAINMENTS_SOCIAL_PRIVELEGES = False
INSTA_URL = "url"
INSTA_TITLE = "title"
INSTA_DATETIME = "datetime"
INSTA_GEO = "geo"

GEO_EPSILON = 0.00000000000001

