# Enthusiasts, 2015

# ETL processing data type
TYPE_DIMENS = 0
TYPE_FACTS = 1

# TODO: REMOVE UNUSED
# json keys
ZONE_TITLE = "ObjectShortName"

POLYGONS_TITLE = "p_title"
POLYGONS_DATA = "polygon"

ENTERTAINMENTS_TITLE = "title"
ENTERTAINMENTS_COST = "cost"
ENTERTAINMENTS_LONGITUDE = "lon"
ENTERTAINMENTS_LATITUDE = "lat"
ENTERTAINMENTS_ZONE_TITLE = "ZoneTitle"
ENTERTAINMENTS_SEAT_COUNT = "seact_count"
ENTERTAINMENTS_SOCIAL_PRIVELEGES = "social_priveleges"

INSTA_URL = "photo_url"
INSTA_USER_URL="page_url"
#INSTA_TITLE = "title"
INSTA_USERNAME = "user_name"
INSTA_DATETIME = "time"
#INSTA_GEO = "geo"
INSTA_LONGTITUDE = "lon"
INSTA_LATITUDE = "lat"

GEO_EPSILON = 0.00000000000001

