# Enthusiasts, 2015

# json keys
ZONE_TITLE = "ObjectShortName"

POLYGONS_TITLE = "p_title"
POLYGONS_DATA = "polygon"

ENTERTAINMENTS_TITLE = "Name"
ENTERTAINMENTS_COST = "cost"
ENTERTAINMENTS_LONGITUDE = "Longitude_WGS84"
ENTERTAINMENTS_LATITUDE = "Latitude_WGS84"
ENTERTAINMENTS_ZONE_TITLE = "District"
ENTERTAINMENTS_SEAT_COUNT = "SeatsCount"
ENTERTAINMENTS_SOCIAL_PRIVELEGES = "SocialPrivileges"
ENTERTAINMENTS_TYPE = "TYPE"

INSTA_URL = "photo_url"
INSTA_USER_URL="page_url"
#INSTA_TITLE = "title"
INSTA_USERNAME = "user_name"
INSTA_DATETIME = "time"
#INSTA_GEO = "geo"
INSTA_LONGTITUDE = "lon"
INSTA_LATITUDE = "lat"

GEO_EPSILON = 0.0000000001

VARCHAR_MAXNUMBER = 140

